### ISSUE TITLE
output JSON file contains a BOM

### ISSUE THREAD

**Issue by williballenthin** [woanware/etw-event-dumper#1]
The JSON files created by this tool have a byte-order mark (BOM); however, this is apparently [invalid JSON](https://stackoverflow.com/a/38036753/87207). I noticed this when I tried to inspect the output document with [jless](https://jless.io/) and it complained (not your problem, just context).

![image](https://user-images.githubusercontent.com/156560/155812217-61b50789-3dad-47b9-af9e-451fba1ebb14.png)

Would you please consider tweaking the output to remove the BOM?

**Comment by woanware** [comment]
Thanks for reporting, should be fixed in v1.0.1!
